CREATE TABLE "ban" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ban_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 92233720368547 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" text NOT NULL,
	CONSTRAINT "ban_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "portfolio" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 922337203685477 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"title" text NOT NULL,
	"draft" boolean DEFAULT true NOT NULL,
	"overview" text DEFAULT '' NOT NULL,
	"shortDescription" text DEFAULT 'Lorem ipsum dolor sit amet' NOT NULL,
	"description" text DEFAULT '' NOT NULL,
	"github_url" text NOT NULL,
	"live_url" text NOT NULL,
	"author" text DEFAULT 'Cały zespół' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "portfolio_project_feature" (
	"content" text DEFAULT 'Lorem ipsum' NOT NULL,
	"order" bigint DEFAULT 0 NOT NULL,
	"portfolioId" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "portfolio_image" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_image_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 922337203685477 START WITH 1 CACHE 1),
	"order" bigint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"path" text,
	"label" text,
	"portfolio_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "portfolio_tech" (
	"id" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "portfolio_tech_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 922337203685477 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"portfolio_id" bigint NOT NULL,
	"tech_id" bigint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tech" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "technologies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 922337203685477 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"icon" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "auth"."users" (
	"id" uuid PRIMARY KEY NOT NULL
);
--> statement-breakpoint
ALTER TABLE "project" DROP CONSTRAINT "project_user_id_fkey";
--> statement-breakpoint
ALTER TABLE "project" ALTER COLUMN "id" SET MAXVALUE 92233720368547;--> statement-breakpoint
ALTER TABLE "portfolio_project_feature" ADD CONSTRAINT "portfolio_project_feature_portfolioId_portfolio_id_fk" FOREIGN KEY ("portfolioId") REFERENCES "public"."portfolio"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portfolio_image" ADD CONSTRAINT "portfolio_image_portfolio_id_portfolio_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolio"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portfolio_tech" ADD CONSTRAINT "portfolio_tech_portfolio_id_portfolio_id_fk" FOREIGN KEY ("portfolio_id") REFERENCES "public"."portfolio"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "portfolio_tech" ADD CONSTRAINT "portfolio_tech_tech_id_tech_id_fk" FOREIGN KEY ("tech_id") REFERENCES "public"."tech"("id") ON DELETE no action ON UPDATE no action;